services:
  backend:
    build: ./backend
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - FRONTEND_ORIGIN=http://localhost:3000
      - JWT_SECRET=dev-secret
      - COOKIE_SECURE=0
      - COOKIE_NAME=refreshToken
      - LDAP_URL=ldap://ldap:389
      - LDAP_BASE_DN=dc=example,dc=org
      - REFRESH_TTL_SECONDS=604800
      - "REFRESH_PREFIX=refresh:"
      - "REVOKED_JTI_PREFIX=revoked_jti:"
      - CHAT_CHANNEL=mini_snap_chat_channel
      - CHAT_STREAM=mini_snap_chat_stream
      - "LAST_READ_PREFIX=chat_last_read:"
      - "SNAP_PREFIX=snap:"
      - UPLOADS_DIR=/app/uploads
      - PORT=5000

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ldap:
    image: osixia/openldap:1.5.0
    environment:
      - LDAP_ORGANISATION=Example Org
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=admin
    volumes:
      - ./backend/ldap/init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif:ro
    ports:
      - "389:389"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    ports:
      - "6443:6443"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE: "http://localhost:5000"
        REACT_APP_WS_BASE: "ws://localhost:5000"
        REACT_APP_FRONTEND_ORIGIN: "http://localhost:3000"
    env_file:
      - ./.env
    ports:
      # The CRA dev server inside the container is listening on 5000 (see container logs).
      # Map host port 3000 to container port 5000 so the app is reachable at http://localhost:3000
      - "3000:5000"
    stdin_open: true
    tty: true

volumes:
  redis_data:
  postgres_data:
